version: 2

publications:
  - url: https://www.npmjs.com/package/launchdarkly-js-test-helpers
    description: npm

jobs:
  - docker:
      image: node:12-buster
    template:
      name: npm

documentation:
  gitHubPages: true
  title: LaunchDarkly JavaScript Test Helpers
